title: "Jekyll Ionic"
description: "Integrasi Ionic di Jekyll"
baseurl: "" # "/nama-folder"
url: "https://plus62store.vercel.app"

# Konfigurasi Jekyll
permalink: pretty
timezone: Asia/Jakarta # Sesuaikan dengan zona waktu
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed # Pilihan: expanded, compressed

# Konfigurasi untuk pagination (jika digunakan)
paginate: 5
paginate_path: "/page:num/"

compress_html:
  clippings: all

# Exclude files (agar tidak diproses oleh Jekyll)
exclude:
  - Gemfile.lock
  - package-lock.json
  - node_modules
  - vendor
  - README.md