# Welcome to Jekyll!

dev: Plus62store

# Site settings
title: Plus62store
description: Jual Masker Bordir Tasikmalaya.
baseurl: ""
url: "https://plus62webstore.pages.dev"
twitter_url:

# Markdown settings
markdown: kramdown

permalink: /:title

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Custom Collections
collections:
  products:
    output: true
    
# Build settings
exclude:
  - package.json
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# Midtrans
WA_KEY: 6281111191209

sanbox_client: SB-Mid-client-i2KW02MfN9duiyJ9
SNAP_SANDBOX_URL: https://app.sandbox.midtrans.com/snap/snap.js
SNAP_SANDBOX_API: https://payment.sendaljepit.workers.dev/

client_key: Mid-client-8Ttb7R_tAhDjoj9-
SNAP_PRODUCTION_URL: https://app.midtrans.com/snap/snap.js
SNAP_PRODUCTION_API: https://midtrans.sendaljepit.workers.dev/

# Snap Defaults
snap_options:
  - sandbox
  - live

# firebase
apiKey: AIzaSyDGYGM4xah-coe60HdhbglBQyD3uYDevdA
authDomain: plus62webstore.firebaseapp.com
databaseURL: https://plus62webstore-default-rtdb.asia-southeast1.firebasedatabase.app
projectId: plus62webstore
storageBucket: plus62webstore.firebasestorage.app
senderId: 994891709388
appId: 1:994891709388:web:8dc826a78000e9aaf73b69
measurementId: G-1VF7TFYW3Z