title: "Jekyll Ionic"
description: "Integrasi Ionic di Jekyll"
baseurl: "" # "/nama-folder"
url: "https://plus62store.pages.dev"

# Konfigurasi Jekyll
permalink: /LoggedIn/product/:title
timezone: Asia/Jakarta # Sesuaikan dengan zona waktu
markdown: kramdown
text_dev: nDang

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# Google Auth
WA_KEY: 081111191209
SITE_KEY: 6Lf8BdkpAAAAAElS8xJWvKYvFtTvIBMD3GKQn0sz
API_KEY: AIzaSyCh346K5NgNSvVq6Mv817GH_E6cPDurR2s
AUTH_DOMAIN: plus62bordir.firebaseapp.com
DATABASE_URL: https://plus62bordir-default-rtdb.asia-southeast1.firebasedatabase.app
PROJECT_ID: plus62bordir
STORAGE_BUCKET: plus62bordir.appspot.com
SENDER_ID: 787412546935
APP_ID: 1:787412546935:web:919338bbff32eada8cdd72
MEASUREMENT_ID: G-C082YPREP9

sass:
  sass_dir: _sass
  style: compressed # Pilihan: expanded, compressed

# Konfigurasi untuk pagination (jika digunakan)
paginate: 5
paginate_path: "/page:num/"

defaults:
- scope:
    type: posts
  values:
    layout: product

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tags: '/tag/:name/'

compress_html:
  clippings: all

# Exclude files (agar tidak diproses oleh Jekyll)
exclude:
  - Gemfile.lock
  - package-lock.json
  - node_modules
  - vendor
  - README.md