title: "Jekyll Ionic"
description: "Integrasi Ionic di Jekyll"
baseurl: "" # Jika di-root domain, biarkan kosong. Jika di subfolder, isi dengan "/nama-folder"
url: "http://localhost:4000" # Ubah saat deploy

# Konfigurasi Jekyll
permalink: pretty
timezone: Asia/Jakarta # Sesuaikan dengan zona waktu
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed # Pilihan: expanded, compressed

# Konfigurasi untuk pagination (jika digunakan)
paginate: 5
paginate_path: "/page:num/"

# Exclude files (agar tidak diproses oleh Jekyll)
exclude:
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md